# Generated by Django 5.0.6 on 2024-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='3af48988-9b2d-4436-9010-b87cb60e9475', max_length=255),
        ),
    ]
