# Generated by Django 5.0.6 on 2024-06-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_person_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='47ab02da-2298-4042-8c41-da678c9365b4', max_length=255),
        ),
    ]
