# Generated by Django 5.0.6 on 2024-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_at_alter_person_profileid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='898a9e70-c5f9-4077-8f01-8871ea931f57', max_length=255),
        ),
    ]
