# Generated by Django 5.0.6 on 2024-06-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_person_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='8fdfc110-4827-4512-8349-ee9408143d9d', max_length=255),
        ),
    ]
