# Generated by Django 5.0.6 on 2024-06-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_person_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='0e66d6ee-8869-4da9-b0b6-52b3981b06e3', max_length=255),
        ),
    ]
