# Generated by Django 5.0.6 on 2024-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_person_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='ec8038c0-4d5d-436f-bb84-1b1e7c9edba0', max_length=255),
        ),
    ]
